spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:postgresql://localhost:5432/video_hosting
    username: postgres
    password: 87654321
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
  liquibase:
    enabled: true
    change-log: liquibase/db.changelog-master.yaml
  data:
    web:
      pageable:
        default-page-size: 10
        max-page-size: 20
  servlet:
    multipart:
      max-file-size: 100KB
      max-request-size: 100KB