--liquibase formatted sql
--changeset Minich_Nikolay:4
INSERT INTO users (nickname, name, email)
VALUES ('alice', 'Alice Smith', 'alice@gmail.com'),
       ('bob', 'Bob Jones', 'bob@yahoo.com'),
       ('charlie', 'Charlie Brown', 'charlie@hotmail.com'),
       ('david', 'David Lee', 'david@outlook.com'),
       ('emma', 'Emma Watson', 'emma@icloud.com'),
       ('frank', 'Frank Sinatra', 'frank@gmail.com'),
       ('grace', 'Grace Kelly', 'grace@yahoo.com'),
       ('harry', 'Harry Potter', 'harry@hotmail.com'),
       ('isabel', 'Isabel Green', 'isabel@outlook.com'),
       ('jack', 'Jack Sparrow', 'jack@icloud.com'),
       ('kate', 'Kate Middleton', 'kate@gmail.com'),
       ('leo', 'Leo Messi', 'leo@yahoo.com'),
       ('maya', 'Maya Angelou', 'maya@hotmail.com'),
       ('nick', 'Nick Fury', 'nick@outlook.com'),
       ('olivia', 'Olivia Wilde', 'olivia@icloud.com'),
       ('peter', 'Peter Parker', 'peter@gmail.com'),
       ('quinn', 'Quinn Fabray', 'quinn@yahoo.com'),
       ('rachel', 'Rachel Berry', 'rachel@hotmail.com'),
       ('sam', 'Sam Wilson', 'sam@outlook.com'),
       ('tina', 'Tina Cohen-Chang', 'tina@icloud.com'),
       ('uma', 'Uma Thurman', 'uma@gmail.com'),
       ('victor', 'Victor Hugo', 'victor@yahoo.com'),
       ('wanda', 'Wanda Maximoff', 'wanda@hotmail.com'),
       ('xavier', 'Xavier Woods', 'xavier@outlook.com'),
       ('yara', 'Yara Greyjoy', 'yara@icloud.com'),
       ('zack', 'Zack Snyder', 'zack@gmail.com'),
       ('anna', 'Anna Karenina', 'anna@yahoo.com'),
       ('ben', 'Ben Affleck', 'ben@hotmail.com'),
       ('clara', 'Clara Oswald', 'clara@outlook.com'),
       ('dan', 'Dan Brown', 'dan@icloud.com');